// lib/mock-data.ts — sample seed for the in-memory data layer.
// Step 10 deletes this file and switches DataProvider to Prisma.

import type { Client, FollowUp, Policy } from "./types";

export const seedClients: Client[] = [
  {
    id: "cli_zhang",
    firstName: "Wei",
    lastName: "Zhang",
    email: "wei.zhang@example.com",
    phone: "(416) 555-0142",
    birthday: "1978-05-12",
    streetAddress: "123 Bay St",
    city: "Toronto",
    province: "ON",
    postalCode: "M5J 2T3",
    notes: "Long-term planning focus, two children.",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "cli_chen",
    firstName: "Li",
    lastName: "Chen",
    email: "li.chen@example.com",
    phone: "(905) 555-0188",
    birthday: "1985-09-23",
    streetAddress: "456 King St W",
    city: "Mississauga",
    province: "ON",
    postalCode: "L5B 4G7",
    createdAt: "2024-03-08T12:00:00Z",
  },
  {
    id: "cli_wang",
    firstName: "Mei",
    lastName: "Wang",
    email: "mei.wang@example.com",
    phone: "(604) 555-0203",
    birthday: "1972-05-22",
    streetAddress: "789 Granville St",
    city: "Vancouver",
    province: "BC",
    postalCode: "V6Z 1K3",
    notes: "Owns import/export business; interested in estate planning.",
    createdAt: "2023-06-22T09:00:00Z",
  },
  {
    id: "cli_liu",
    firstName: "David",
    lastName: "Liu",
    email: "david.liu@example.com",
    phone: "(437) 555-0291",
    birthday: "1990-11-04",
    streetAddress: "10 Front St E",
    unit: "Suite 1402",
    city: "Toronto",
    province: "ON",
    postalCode: "M5E 1B3",
    createdAt: "2024-09-12T15:00:00Z",
  },
  {
    id: "cli_huang",
    firstName: "Sarah",
    lastName: "Huang",
    email: "sarah.huang@example.com",
    phone: "(647) 555-0344",
    birthday: "1982-05-29",
    streetAddress: "200 University Ave",
    city: "Toronto",
    province: "ON",
    postalCode: "M5H 3C6",
    // Linked back to spouse Wei Zhang — exercises the self-referencing link.
    linkedToId: "cli_zhang",
    relationship: "Spouse",
    createdAt: "2023-11-05T11:00:00Z",
  },
  {
    id: "cli_tang",
    firstName: "Robert",
    lastName: "Tang",
    email: "robert.tang@example.com",
    phone: "(403) 555-0419",
    birthday: "1968-02-14",
    streetAddress: "55 Centre St N",
    city: "Calgary",
    province: "AB",
    postalCode: "T2E 2A8",
    createdAt: "2022-08-30T14:00:00Z",
  },
  {
    id: "cli_zhao",
    firstName: "Jessica",
    lastName: "Zhao",
    email: "jessica.zhao@example.com",
    phone: "(416) 555-0507",
    birthday: "1995-07-18",
    streetAddress: "300 Front St W",
    city: "Toronto",
    province: "ON",
    postalCode: "M5V 0E9",
    // Recent onboarding — within the 3-month "New" cohort window.
    createdAt: "2026-04-10T16:00:00Z",
  },
];

// Build a Policy from a seed entry. Premium Date is only meaningful for
// Insurance + Annually — for everything else we leave it undefined. Stored
// in canonical "MM-DD" form (year-less); display layer renders as "Oct 24".
function makePolicy(partial: Omit<Policy, "premiumDate">): Policy {
  const isAnnualInsurance =
    partial.category === "Insurance" && partial.paymentFrequency === "Annual";
  return {
    ...partial,
    premiumDate: isAnnualInsurance
      ? partial.effectiveDate.slice(5, 10) // "YYYY-MM-DD" → "MM-DD"
      : undefined,
  };
}

export const seedPolicies: Policy[] = [
  makePolicy({
    id: "pol_zhang_life",
    clientId: "cli_zhang",
    carrier: "Manulife",
    category: "Insurance",
    productType: "Whole Life",
    productName: "Manulife UL ParticiPlus",
    policyNumber: "MAN-887412",
    sumAssured: 1_000_000,
    premium: 480,
    paymentFrequency: "Monthly",
    effectiveDate: "2022-06-15",
    status: "active",
    beneficiaries: [],
  }),
  makePolicy({
    id: "pol_chen_ci",
    clientId: "cli_chen",
    carrier: "Sun Life",
    category: "Insurance",
    productType: "Critical Illness",
    productName: "Sun CI Lifetime",
    policyNumber: "SUN-552093",
    sumAssured: 250_000,
    premium: 7400,
    paymentFrequency: "Annual",
    effectiveDate: "2023-08-22",
    status: "active",
    beneficiaries: [],
  }),
  makePolicy({
    id: "pol_wang_life",
    clientId: "cli_wang",
    carrier: "Canada Life",
    category: "Insurance",
    productType: "Whole Life",
    productName: "Canada Life My Par Gold",
    policyNumber: "CL-104228",
    sumAssured: 2_500_000,
    premium: 12000,
    paymentFrequency: "Annual",
    effectiveDate: "2021-04-10",
    status: "active",
    beneficiaries: [],
  }),
  makePolicy({
    id: "pol_liu_term",
    clientId: "cli_liu",
    carrier: "Equitable Life",
    category: "Insurance",
    productType: "Term Insurance",
    productName: "Equitable Term 20",
    policyNumber: "EL-330176",
    sumAssured: 500_000,
    premium: 92,
    paymentFrequency: "Monthly",
    effectiveDate: "2024-10-01",
    status: "active",
    beneficiaries: [],
  }),
  makePolicy({
    id: "pol_huang_life",
    clientId: "cli_huang",
    carrier: "Sun Life",
    category: "Insurance",
    productType: "Whole Life",
    productName: "Sun Par Protector II",
    policyNumber: "SUN-771204",
    sumAssured: 750_000,
    premium: 12800,
    paymentFrequency: "Annual",
    effectiveDate: "2023-02-12",
    status: "active",
    beneficiaries: [],
  }),
  makePolicy({
    id: "pol_tang_term",
    clientId: "cli_tang",
    carrier: "Manulife",
    category: "Insurance",
    productType: "Term Insurance",
    productName: "Manulife Term 10",
    policyNumber: "MAN-220514",
    sumAssured: 250_000,
    premium: 145,
    paymentFrequency: "Monthly",
    effectiveDate: "2020-03-01",
    status: "active",
    beneficiaries: [],
  }),
];

export const seedFollowUps: FollowUp[] = [
  {
    id: "fup_1",
    clientId: "cli_wang",
    type: "Meeting",
    date: "2026-04-28",
    summary: "Annual review meeting",
    details: "Reviewed performance of Par Gold policy and segregated fund. Discussed adding spousal RRSP next quarter.",
    createdById: "user_admin",
    createdByName: "Admin",
    createdAt: "2026-04-28T15:30:00Z",
  },
  {
    id: "fup_2",
    clientId: "cli_zhang",
    type: "Phone",
    date: "2026-04-22",
    summary: "Premium adjustment discussion",
    details: "Wei wants to top up by $200/mo starting June.",
    createdById: "user_admin",
    createdByName: "Admin",
    createdAt: "2026-04-22T14:15:00Z",
  },
  {
    id: "fup_3",
    clientId: "cli_chen",
    type: "Email",
    date: "2026-05-02",
    summary: "Sent illustration for non-registered account",
    createdById: "user_admin",
    createdByName: "Admin",
    createdAt: "2026-05-02T09:45:00Z",
  },
];
