#!/bin/sh
# scripts/migrate-cloudflared-to-credentials.sh
#
# One-time migration: switch the cloudflared container from token mode
# to credentials-file mode. Token mode leaks the tunnel token through
# `docker inspect` and the container command line, which is enough for
# an attacker to hijack the public hostname.
#
# Prerequisite (do this on a desktop with a browser, NOT on the NAS):
#   1. brew install cloudflared   (or download from cloudflare.com)
#   2. cloudflared tunnel login
#   3. cloudflared tunnel list
#      Find the existing tunnel (likely already named for triton-crm).
#      Copy the UUID from the first column.
#   4. cloudflared tunnel token --cred-file ./triton.json <UUID>
#      This dumps the credentials JSON for the existing tunnel without
#      creating a new one — important so you don't have to re-route DNS.
#   5. scp triton.json wellce101@192.168.50.158:/tmp/triton-cred.json
#
# Then run THIS script on the NAS:
#   bash scripts/migrate-cloudflared-to-credentials.sh
set -eu

REPO_DIR="/volume1/docker/triton-crm"
CRED_DIR="$REPO_DIR/cloudflared"
SOURCE_CRED="/tmp/triton-cred.json"
HOSTNAME_FQDN="crm.tritonwealth.ca"
SERVICE_URL="http://triton-crm:3000"
COMPOSE_FILE="$REPO_DIR/docker/docker-compose.yml"

if [ ! -f "$SOURCE_CRED" ]; then
  echo "!!! $SOURCE_CRED not found."
  echo "    Generate it on a desktop first (see header of this script)."
  exit 1
fi

cd "$REPO_DIR"
mkdir -p "$CRED_DIR"
chmod 700 "$CRED_DIR"

# Extract tunnel UUID from the credentials file.
TUNNEL_UUID="$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['TunnelID'])" "$SOURCE_CRED" 2>/dev/null || true)"
if [ -z "$TUNNEL_UUID" ]; then
  echo "!!! Could not read TunnelID from $SOURCE_CRED."
  echo "    The file should contain a JSON object with TunnelID, AccountTag, TunnelSecret."
  exit 1
fi
echo "==> Tunnel UUID: $TUNNEL_UUID"

cp "$SOURCE_CRED" "$CRED_DIR/credentials.json"
chmod 600 "$CRED_DIR/credentials.json"
echo "==> Credentials installed at $CRED_DIR/credentials.json (mode 600)"

cat > "$CRED_DIR/config.yml" <<CONFIG
# Cloudflare Tunnel config — generated by migrate-cloudflared-to-credentials.sh
tunnel: $TUNNEL_UUID
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: $HOSTNAME_FQDN
    service: $SERVICE_URL
  # Catch-all: any request that does not match the hostname above is
  # rejected at the tunnel edge instead of being forwarded.
  - service: http_status:404
CONFIG
chmod 640 "$CRED_DIR/config.yml"
echo "==> config.yml written for $HOSTNAME_FQDN -> $SERVICE_URL"

echo "==> Restarting cloudflared with the new credentials"
cd "$(dirname "$COMPOSE_FILE")"
docker compose up -d cloudflared

echo "==> Waiting for tunnel to register..."
sleep 8
docker logs --tail 20 triton-tunnel || true

echo
echo "==> Migration complete."
echo "    Verify: curl -I https://$HOSTNAME_FQDN"
echo "    If healthy, remove CLOUDFLARED_TOKEN from .env.production and shred the host copy:"
echo "      shred -u $SOURCE_CRED 2>/dev/null || rm -f $SOURCE_CRED"
